server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions: 
  filename: /tmp/positions.yaml

clients:
  - url: http://localhost:3100/loki/api/v1/push

scrape_configs:
  - job_name: nomad-logs
    static_configs:
      - targets:
	- localhost
	labels:
	  job: nomad
	  __path__: /nomad/nomad.log
